package com.proyectograduacion.PGwebONG.domain.direccion;

import lombok.Getter;

@Getter
public enum CodigoUbicaciones {

//    GUATEMALA
GUATEMALA_GUATEMALA("0101", "01", "Guatemala", "01", "Guatemala"),
    GUATEMALA_SANTA_CATARINA_PINULA("0102", "01", "Guatemala", "02", "Santa Catarina Pinula"),
    GUATEMALA_SAN_JOSE_PINULA("0103", "01", "Guatemala", "03", "San José Pinula"),
    GUATEMALA_SAN_JOSE_DEL_GOLFO("0104", "01", "Guatemala", "04", "San José del Golfo"),
    GUATEMALA_PALENCIA("0105", "01", "Guatemala", "05", "Palencia"),
    GUATEMALA_CHINAUTLA("0106", "01", "Guatemala", "06", "Chinautla"),
    GUATEMALA_SAN_PEDRO_AYAMPUC("0107", "01", "Guatemala", "07", "San Pedro Ayampuc"),
    GUATEMALA_MIXCO("0108", "01", "Guatemala", "08", "Mixco"),
    GUATEMALA_SAN_PEDRO_SACATEPEQUEZ("0109", "01", "Guatemala", "09", "San Pedro Sacatepéquez"),
    GUATEMALA_SAN_JUAN_SACATEPEQUEZ("0110", "01", "Guatemala", "10", "San Juan Sacatepéquez"),
    GUATEMALA_SAN_RAYMUNDO("0111", "01", "Guatemala", "11", "San Raymundo"),
    GUATEMALA_CHUARRANCHO("0112", "01", "Guatemala", "12", "Chuarrancho"),
    GUATEMALA_FRAIJANES("0113", "01", "Guatemala", "13", "Fraijanes"),
    GUATEMALA_AMATITLAN("0114", "01", "Guatemala", "14", "Amatitlán"),
    GUATEMALA_VILLA_NUEVA("0115", "01", "Guatemala", "15", "Villa Nueva"),
    GUATEMALA_VILLA_CANALES("0116", "01", "Guatemala", "16", "Villa Canales"),
    GUATEMALA_SAN_MIGUEL_PETAPA("0117", "01", "Guatemala", "17", "San Miguel Petapa"),

//    EL_PROGRESO
EL_PROGRESO_GUASTATOYA("0201", "02", "El Progreso", "01", "Guastatoya"),
    EL_PROGRESO_MORAZAN("0202", "02", "El Progreso", "02", "Morazán"),
    EL_PROGRESO_SAN_AGUSTIN_ACASAGUASTLAN("0203", "02", "El Progreso", "03", "San Agustín Acasaguastlán"),
    EL_PROGRESO_SAN_CRISTOBAL_ACASAGUASTLAN("0204", "02", "El Progreso", "04", "San Cristóbal Acasaguastlán"),
    EL_PROGRESO_EL_JICARO("0205", "02", "El Progreso", "05", "El Jícaro"),
    EL_PROGRESO_SANSARE("0206", "02", "El Progreso", "06", "Sansare"),
    EL_PROGRESO_SANARATE("0207", "02", "El Progreso", "07", "Sanarate"),
    EL_PROGRESO_SAN_ANTONIO_LA_PAZ("0208", "02", "El Progreso", "08", "San Antonio La Paz"),

    //    SACATEPEQUEZ
    SACATEPEQUEZ_ANTIGUA("0301", "03", "Sacatepéquez", "01", "Antigua Guatemala"),
    SACATEPEQUEZ_JOCOTENANGO("0302", "03", "Sacatepéquez", "02", "Jocotenango"),
    SACATEPEQUEZ_PASTORES("0303", "03", "Sacatepéquez", "03", "Pastores"),
    SACATEPEQUEZ_SUMPANGO("0304", "03", "Sacatepéquez", "04", "Sumpango"),
    SACATEPEQUEZ_SANTO_DOMINGO_XENACOJ("0305", "03", "Sacatepéquez", "05", "Santo Domingo Xenacoj"),
    SACATEPEQUEZ_SANTIAGO_SACATEPEQUEZ("0306", "03", "Sacatepéquez", "06", "Santiago Sacatepéquez"),
    SACATEPEQUEZ_SAN_BARTOLOME_MILPAS_ALTAS("0307", "03", "Sacatepéquez", "07", "San Bartolomé Milpas Altas"),
    SACATEPEQUEZ_SAN_LUCAS_SACATEPEQUEZ("0308", "03", "Sacatepéquez", "08", "San Lucas Sacatepéquez"),
    SACATEPEQUEZ_SANTA_LUCIA_MILPAS_ALTAS("0309", "03", "Sacatepéquez", "09", "Santa Lucía Milpas Altas"),
    SACATEPEQUEZ_MAGDALENA_MILPAS_ALTAS("0310", "03", "Sacatepéquez", "10", "Magdalena Milpas Altas"),
    SACATEPEQUEZ_SANTA_MARIA_DE_JESUS("0311", "03", "Sacatepéquez", "11", "Santa María de Jesús"),
    SACATEPEQUEZ_CIUDAD_VIEJA("0312", "03", "Sacatepéquez", "12", "Ciudad Vieja"),
    SACATEPEQUEZ_SAN_MIGUEL_DUENAS("0313", "03", "Sacatepéquez", "13", "San Miguel Dueñas"),
    SACATEPEQUEZ_ALOTENANGO("0314", "03", "Sacatepéquez", "14", "Alotenango"),
    SACATEPEQUEZ_SAN_ANTONIO_AGUAS_CALIENTES("0315", "03", "Sacatepéquez", "15", "San Antonio Aguas Calientes"),
    SACATEPEQUEZ_SANTA_CATARINA_BARAHONA("0316", "03", "Sacatepéquez", "16", "Santa Catarina Barahona"),

//    CHIMALTENANGO
CHIMALTENANGO_CHIMALTENANGO("0401", "04", "Chimaltenango", "01", "Chimaltenango"),
    CHIMALTENANGO_SAN_JOSE_POAQUIL("0402", "04", "Chimaltenango", "02", "San José Poaquil"),
    CHIMALTENANGO_SAN_MARTIN_JILOTEPEQUE("0403", "04", "Chimaltenango", "03", "San Martín Jilotepeque"),
    CHIMALTENANGO_SAN_JUAN_COMALAPA("0404", "04", "Chimaltenango", "04", "San Juan Comalapa"),
    CHIMALTENANGO_SANTA_APOLONIA("0405", "04", "Chimaltenango", "05", "Santa Apolonia"),
    CHIMALTENANGO_TECPAN_GUATEMALA("0406", "04", "Chimaltenango", "06", "Tecpán Guatemala"),
    CHIMALTENANGO_PATZUN("0407", "04", "Chimaltenango", "07", "Patzún"),
    CHIMALTENANGO_SAN_MIGUEL_POCHUTA("0408", "04", "Chimaltenango", "08", "San Miguel Pochuta"),
    CHIMALTENANGO_PATZICIA("0409", "04", "Chimaltenango", "09", "Patzicía"),
    CHIMALTENANGO_SANTA_CRUZ_BALANYA("0410", "04", "Chimaltenango", "10", "Santa Cruz Balanyá"),
    CHIMALTENANGO_ACATENANGO("0411", "04", "Chimaltenango", "11", "Acatenango"),
    CHIMALTENANGO_SAN_PEDRO_YEPOCAPA("0412", "04", "Chimaltenango", "12", "San Pedro Yepocapa"),
    CHIMALTENANGO_SAN_ANDRES_ITZAPA("0413", "04", "Chimaltenango", "13", "San Andrés Itzapa"),
    CHIMALTENANGO_PARRAMOS("0414", "04", "Chimaltenango", "14", "Parramos"),
    CHIMALTENANGO_ZARAGOZA("0415", "04", "Chimaltenango", "15", "Zaragoza"),
    CHIMALTENANGO_EL_TEJAR("0416", "04", "Chimaltenango", "16", "El Tejar"),

//    ESCUINTLA
ESCUINTLA_ESCUINTLA("0501", "05", "Escuintla", "01", "Escuintla"),
    ESCUINTLA_SANTA_LUCIA_COTZUMALGUAPA("0502", "05", "Escuintla", "02", "Santa Lucía Cotzumalguapa"),
    ESCUINTLA_LA_DEMOCRACIA("0503", "05", "Escuintla", "03", "La Democracia"),
    ESCUINTLA_SIQUINALA("0504", "05", "Escuintla", "04", "Siquinalá"),
    ESCUINTLA_MASAGUA("0505", "05", "Escuintla", "05", "Masagua"),
    ESCUINTLA_TIQUISATE("0506", "05", "Escuintla", "06", "Tiquisate"),
    ESCUINTLA_LA_GOMERA("0507", "05", "Escuintla", "07", "La Gomera"),
    ESCUINTLA_GUANAGAZAPA("0508", "05", "Escuintla", "08", "Guanagazapa"),
    ESCUINTLA_SAN_JOSE("0509", "05", "Escuintla", "09", "San José"),
    ESCUINTLA_IZTAPA("0510", "05", "Escuintla", "10", "Iztapa"),
    ESCUINTLA_PALIN("0511", "05", "Escuintla", "11", "Palín"),
    ESCUINTLA_SAN_VICENTE_PACAYA("0512", "05", "Escuintla", "12", "San Vicente Pacaya"),
    ESCUINTLA_NUEVA_CONCEPCION("0513", "05", "Escuintla", "13", "Nueva Concepción"),

//    SANTA_ROSA
SANTA_ROSA_CUILAPA("0601", "06", "Santa Rosa", "01", "Cuilapa"),
    SANTA_ROSA_BARBERENA("0602", "06", "Santa Rosa", "02", "Barberena"),
    SANTA_ROSA_SANTA_ROSA_DE_LIMA("0603", "06", "Santa Rosa", "03", "Santa Rosa de Lima"),
    SANTA_ROSA_CASILLAS("0604", "06", "Santa Rosa", "04", "Casillas"),
    SANTA_ROSA_SAN_RAFAEL_LAS_FLORES("0605", "06", "Santa Rosa", "05", "San Rafael Las Flores"),
    SANTA_ROSA_ORATORIO("0606", "06", "Santa Rosa", "06", "Oratorio"),
    SANTA_ROSA_SAN_JUAN_TECUACO("0607", "06", "Santa Rosa", "07", "San Juan Tecuaco"),
    SANTA_ROSA_CHIQUIMULILLA("0608", "06", "Santa Rosa", "08", "Chiquimulilla"),
    SANTA_ROSA_TAXISCO("0609", "06", "Santa Rosa", "09", "Taxisco"),
    SANTA_ROSA_SANTA_MARIA_IXHUATAN("0610", "06", "Santa Rosa", "10", "Santa María Ixhuatán"),
    SANTA_ROSA_GUAZACAPAN("0611", "06", "Santa Rosa", "11", "Guazacapán"),
    SANTA_ROSA_SANTA_CRUZ_NARANJO("0612", "06", "Santa Rosa", "12", "Santa Cruz Naranjo"),
    SANTA_ROSA_PUEBLO_NUEVO_VINAS("0613", "06", "Santa Rosa", "13", "Pueblo Nuevo Viñas"),
    SANTA_ROSA_NUEVA_SANTA_ROSA("0614", "06", "Santa Rosa", "14", "Nueva Santa Rosa"),

//    SOLOLA
SOLOLA_SOLOLA("0701", "07", "Sololá", "01", "Sololá"),
    SOLOLA_SAN_JOSE_CHACAYA("0702", "07", "Sololá", "02", "San José Chacayá"),
    SOLOLA_SANTA_MARIA_VISITACION("0703", "07", "Sololá", "03", "Santa María Visitación"),
    SOLOLA_SANTA_LUCIA_UTATLAN("0704", "07", "Sololá", "04", "Santa Lucía Utatlán"),
    SOLOLA_NAHUALA("0705", "07", "Sololá", "05", "Nahualá"),
    SOLOLA_SANTA_CATARINA_IXTAHUACAN("0706", "07", "Sololá", "06", "Santa Catarina Ixtahuacán"),
    SOLOLA_SANTA_CLARA_LA_LAGUNA("0707", "07", "Sololá", "07", "Santa Clara La Laguna"),
    SOLOLA_CONCEPCION("0708", "07", "Sololá", "08", "Concepción"),
    SOLOLA_SAN_ANDRES_SEMETABAJ("0709", "07", "Sololá", "09", "San Andrés Semetabaj"),
    SOLOLA_PANAJACHEL("0710", "07", "Sololá", "10", "Panajachel"),
    SOLOLA_SANTA_CATARINA_PALOPO("0711", "07", "Sololá", "11", "Santa Catarina Palopó"),
    SOLOLA_SAN_ANTONIO_PALOPO("0712", "07", "Sololá", "12", "San Antonio Palopó"),
    SOLOLA_SAN_LUCAS_TOLIMAN("0713", "07", "Sololá", "13", "San Lucas Tolimán"),
    SOLOLA_SANTA_CRUZ_LA_LAGUNA("0714", "07", "Sololá", "14", "Santa Cruz La Laguna"),
    SOLOLA_SAN_PABLO_LA_LAGUNA("0715", "07", "Sololá", "15", "San Pablo La Laguna"),
    SOLOLA_SAN_MARCOS_LA_LAGUNA("0716", "07", "Sololá", "16", "San Marcos La Laguna"),
    SOLOLA_SAN_JUAN_LA_LAGUNA("0717", "07", "Sololá", "17", "San Juan La Laguna"),
    SOLOLA_SAN_PEDRO_LA_LAGUNA("0718", "07", "Sololá", "18", "San Pedro La Laguna"),
    SOLOLA_SANTIAGO_ATITLAN("0719", "07", "Sololá", "19", "Santiago Atitlán"),


//    TOTONICAPAN
TOTONICAPAN_TOTONICAPAN("0801", "08", "Totonicapán", "01", "Totonicapán"),
    TOTONICAPAN_SAN_CRISTOBAL_TOTONICAPAN("0802", "08", "Totonicapán", "02", "San Cristóbal Totonicapán"),
    TOTONICAPAN_SAN_FRANCISCO_EL_ALTO("0803", "08", "Totonicapán", "03", "San Francisco El Alto"),
    TOTONICAPAN_SAN_ANDRES_XECUL("0804", "08", "Totonicapán", "04", "San Andrés Xecul"),
    TOTONICAPAN_MOMOSTENANGO("0805", "08", "Totonicapán", "05", "Momostenango"),
    TOTONICAPAN_SANTA_MARIA_CHIQUIMULA("0806", "08", "Totonicapán", "06", "Santa María Chiquimula"),
    TOTONICAPAN_SANTA_LUCIA_LA_REFORMA("0807", "08", "Totonicapán", "07", "Santa Lucía La Reforma"),
    TOTONICAPAN_SAN_BARTOLO_AGUAS_CALIENTES("0808", "08", "Totonicapán", "08", "San Bartolo Aguas Calientes"),


//    QUETZALTENANGO

    QUETZALTENANGO_QUETZALTENANGO("0901", "09", "Quetzaltenango", "01", "Quetzaltenango"),
    QUETZALTENANGO_SALCAJA("0902", "09", "Quetzaltenango", "02", "Salcajá"),
    QUETZALTENANGO_OLINTEPEQUE("0903", "09", "Quetzaltenango", "03", "Olintepeque"),
    QUETZALTENANGO_SAN_CARLOS_SIJA("0904", "09", "Quetzaltenango", "04", "San Carlos Sija"),
    QUETZALTENANGO_SIBILIA("0905", "09", "Quetzaltenango", "05", "Sibilia"),
    QUETZALTENANGO_CABRICAN("0906", "09", "Quetzaltenango", "06", "Cabricán"),
    QUETZALTENANGO_CAJOLA("0907", "09", "Quetzaltenango", "07", "Cajolá"),
    QUETZALTENANGO_SAN_MIGUEL_SIGUILA("0908", "09", "Quetzaltenango", "08", "San Miguel Siguilá"),
    QUETZALTENANGO_SAN_JUAN_OSTUNCALCO("0909", "09", "Quetzaltenango", "09", "San Juan Ostuncalco"),
    QUETZALTENANGO_SAN_MATEO("0910", "09", "Quetzaltenango", "10", "San Mateo"),
    QUETZALTENANGO_CONCEPCION_CHIQUIRICHAPA("0911", "09", "Quetzaltenango", "11", "Concepción Chiquirichapa"),
    QUETZALTENANGO_SAN_MARTIN_SACATEPEQUEZ("0912", "09", "Quetzaltenango", "12", "San Martín Sacatepéquez"),
    QUETZALTENANGO_ALMOLONGA("0913", "09", "Quetzaltenango", "13", "Almolonga"),
    QUETZALTENANGO_CANTEL("0914", "09", "Quetzaltenango", "14", "Cantel"),
    QUETZALTENANGO_HUITAN("0915", "09", "Quetzaltenango", "15", "Huitán"),
    QUETZALTENANGO_ZUNIL("0916", "09", "Quetzaltenango", "16", "Zunil"),
    QUETZALTENANGO_COLOMBA_COSTA_CUCA("0917", "09", "Quetzaltenango", "17", "Colomba Costa Cuca"),
    QUETZALTENANGO_SAN_FRANCISCO_LA_UNION("0918", "09", "Quetzaltenango", "18", "San Francisco La Unión"),
    QUETZALTENANGO_EL_PALMAR("0919", "09", "Quetzaltenango", "19", "El Palmar"),
    QUETZALTENANGO_COATEPEQUE("0920", "09", "Quetzaltenango", "20", "Coatepeque"),
    QUETZALTENANGO_GENOVA_COSTA_CUCA("0921", "09", "Quetzaltenango", "21", "Génova Costa Cuca"),
    QUETZALTENANGO_FLORES_COSTA_CUCA("0922", "09", "Quetzaltenango", "22", "Flores Costa Cuca"),
    QUETZALTENANGO_LA_ESPERANZA("0923", "09", "Quetzaltenango", "23", "La Esperanza"),
    QUETZALTENANGO_PALESTINA_DE_LOS_ALTOS("0924", "09", "Quetzaltenango", "24", "Palestina de los Altos"),

//    SUCHITEPEQUEZ
    SUCHITEPEQUEZ_MAZATENANGO("1001", "10", "Suchitepéquez", "01", "Mazatenango"),
    SUCHITEPEQUEZ_CUYOTENANGO("1002", "10", "Suchitepéquez", "02", "Cuyotenango"),
    SUCHITEPEQUEZ_SAN_FRANCISCO_ZAPOTITLAN("1003", "10", "Suchitepéquez", "03", "San Francisco Zapotitlán"),
    SUCHITEPEQUEZ_SAN_BERNARDINO("1004", "10", "Suchitepéquez", "04", "San Bernardino"),
    SUCHITEPEQUEZ_SAN_JOSE_EL_IDOLO("1005", "10", "Suchitepéquez", "05", "San José El Ídolo"),
    SUCHITEPEQUEZ_SANTO_DOMINGO_SUCHITEPEQUEZ("1006", "10", "Suchitepéquez", "06", "Santo Domingo Suchitepéquez"),
    SUCHITEPEQUEZ_SAN_LORENZO("1007", "10", "Suchitepéquez", "07", "San Lorenzo"),
    SUCHITEPEQUEZ_SAMAYAC("1008", "10", "Suchitepéquez", "08", "Samayac"),
    SUCHITEPEQUEZ_SAN_PABLO_JOCOPILAS("1009", "10", "Suchitepéquez", "09", "San Pablo Jocopilas"),
    SUCHITEPEQUEZ_SAN_ANTONIO_SUCHITEPEQUEZ("1010", "10", "Suchitepéquez", "10", "San Antonio Suchitepéquez"),
    SUCHITEPEQUEZ_SAN_MIGUEL_PANAM("1011", "10", "Suchitepéquez", "11", "San Miguel Panán"),
    SUCHITEPEQUEZ_SAN_GABRIEL("1012", "10", "Suchitepéquez", "12", "San Gabriel"),
    SUCHITEPEQUEZ_CHICACAO("1013", "10", "Suchitepéquez", "13", "Chicacao"),
    SUCHITEPEQUEZ_PATULUL("1014", "10", "Suchitepéquez", "14", "Patulul"),
    SUCHITEPEQUEZ_SANTA_BARBARA("1015", "10", "Suchitepéquez", "15", "Santa Bárbara"),
    SUCHITEPEQUEZ_SAN_JUAN_BAUTISTA("1016", "10", "Suchitepéquez", "16", "San Juan Bautista"),
    SUCHITEPEQUEZ_SANTO_TOMAS_LA_UNION("1017", "10", "Suchitepéquez", "17", "Santo Tomás La Unión"),
    SUCHITEPEQUEZ_ZUNILITO("1018", "10", "Suchitepéquez", "18", "Zunilito"),
    SUCHITEPEQUEZ_PUEBLO_NUEVO("1019", "10", "Suchitepéquez", "19", "Pueblo Nuevo"),
    SUCHITEPEQUEZ_RIO_BRAVO("1020", "10", "Suchitepéquez", "20", "Río Bravo"),

//    RETALHULEU
RETALHULEU_RETALHULEU("1101", "11", "Retalhuleu", "01", "Retalhuleu"),
    RETALHULEU_SAN_SEBASTIAN("1102", "11", "Retalhuleu", "02", "San Sebastián"),
    RETALHULEU_SANTA_CRUZ_MULUA("1103", "11", "Retalhuleu", "03", "Santa Cruz Muluá"),
    RETALHULEU_SAN_MARTIN_ZAPOTITLAN("1104", "11", "Retalhuleu", "04", "San Martín Zapotitlán"),
    RETALHULEU_SAN_FELIPE("1105", "11", "Retalhuleu", "05", "San Felipe"),
    RETALHULEU_SAN_ANDRES_VILLA_SECA("1106", "11", "Retalhuleu", "06", "San Andrés Villa Seca"),
    RETALHULEU_CHAMPERICO("1107", "11", "Retalhuleu", "07", "Champerico"),
    RETALHULEU_NUEVO_SAN_CARLOS("1108", "11", "Retalhuleu", "08", "Nuevo San Carlos"),
    RETALHULEU_EL_ASINTAL("1109", "11", "Retalhuleu", "09", "El Asintal"),

//    SAN_MARCOS
SAN_MARCOS_SAN_MARCOS("1201", "12", "San Marcos", "01", "San Marcos"),
    SAN_MARCOS_SAN_PEDRO_SACATEPEQUEZ("1202", "12", "San Marcos", "02", "San Pedro Sacatepéquez"),
    SAN_MARCOS_SAN_ANTONIO_SACATEPEQUEZ("1203", "12", "San Marcos", "03", "San Antonio Sacatepéquez"),
    SAN_MARCOS_COMITANCILLO("1204", "12", "San Marcos", "04", "Comitancillo"),
    SAN_MARCOS_SAN_MIGUEL_IXTAHUACAN("1205", "12", "San Marcos", "05", "San Miguel Ixtahuacán"),
    SAN_MARCOS_CONCEPCION_TUTUAPA("1206", "12", "San Marcos", "06", "Concepción Tutuapa"),
    SAN_MARCOS_TACANA("1207", "12", "San Marcos", "07", "Tacaná"),
    SAN_MARCOS_SIBINAL("1208", "12", "San Marcos", "08", "Sibinal"),
    SAN_MARCOS_TAJUMULCO("1209", "12", "San Marcos", "09", "Tajumulco"),
    SAN_MARCOS_TEJUTLA("1210", "12", "San Marcos", "10", "Tejutla"),
    SAN_MARCOS_SAN_RAFAEL_PIE_DE_LA_CUESTA("1211", "12", "San Marcos", "11", "San Rafael Pie de la Cuesta"),
    SAN_MARCOS_NUEVO_PROGRESO("1212", "12", "San Marcos", "12", "Nuevo Progreso"),
    SAN_MARCOS_EL_TUMBADOR("1213", "12", "San Marcos", "13", "El Tumbador"),
    SAN_MARCOS_SAN_JOSE_EL_RODEO("1214", "12", "San Marcos", "14", "San José El Rodeo"),
    SAN_MARCOS_MALACATAN("1215", "12", "San Marcos", "15", "Malacatán"),
    SAN_MARCOS_CATARINA("1216", "12", "San Marcos", "16", "Catarina"),
    SAN_MARCOS_AYUTLA_TECUN_UMAN("1217", "12", "San Marcos", "17", "Ayutla (Tecún Umán)"),
    SAN_MARCOS_OCOS("1218", "12", "San Marcos", "18", "Ocós"),
    SAN_MARCOS_SAN_PABLO("1219", "12", "San Marcos", "19", "San Pablo"),
    SAN_MARCOS_EL_QUETZAL("1220", "12", "San Marcos", "20", "El Quetzal"),
    SAN_MARCOS_LA_REFORMA("1221", "12", "San Marcos", "21", "La Reforma"),
    SAN_MARCOS_PAJAPITA("1222", "12", "San Marcos", "22", "Pajapita"),
    SAN_MARCOS_IXCHIGUAN("1223", "12", "San Marcos", "23", "Ixchiguán"),
    SAN_MARCOS_SAN_JOSE_OJETENAM("1224", "12", "San Marcos", "24", "San José Ojetenam"),
    SAN_MARCOS_SAN_CRISTOBAL_CUCHO("1225", "12", "San Marcos", "25", "San Cristóbal Cucho"),
    SAN_MARCOS_SIPACAPA("1226", "12", "San Marcos", "26", "Sipacapa"),
    SAN_MARCOS_ESQUIPULAS_PALO_GORDO("1227", "12", "San Marcos", "27", "Esquipulas Palo Gordo"),
    SAN_MARCOS_RIO_BLANCO("1228", "12", "San Marcos", "28", "Río Blanco"),
    SAN_MARCOS_SAN_LORENZO("1229", "12", "San Marcos", "29", "San Lorenzo"),

//    HUEHUETENANGO
HUEHUETENANGO_HUEHUETENANGO("1301", "13", "Huehuetenango", "01", "Huehuetenango"),
    HUEHUETENANGO_CHIANTLA("1302", "13", "Huehuetenango", "02", "Chiantla"),
    HUEHUETENANGO_MALACATANCITO("1303", "13", "Huehuetenango", "03", "Malacatancito"),
    HUEHUETENANGO_CUILCO("1304", "13", "Huehuetenango", "04", "Cuilco"),
    HUEHUETENANGO_NENTON("1305", "13", "Huehuetenango", "05", "Nentón"),
    HUEHUETENANGO_SAN_PEDRO_NECTA("1306", "13", "Huehuetenango", "06", "San Pedro Necta"),
    HUEHUETENANGO_JACALTENANGO("1307", "13", "Huehuetenango", "07", "Jacaltenango"),
    HUEHUETENANGO_SAN_PEDRO_SOLOMA("1308", "13", "Huehuetenango", "08", "San Pedro Soloma"),
    HUEHUETENANGO_SAN_ILDEFONSO_IXTAHUACAN("1309", "13", "Huehuetenango", "09", "San Ildefonso Ixtahuacán"),
    HUEHUETENANGO_SANTA_BARBARA("1310", "13", "Huehuetenango", "10", "Santa Bárbara"),
    HUEHUETENANGO_LA_LIBERTAD("1311", "13", "Huehuetenango", "11", "La Libertad"),
    HUEHUETENANGO_LA_DEMOCRACIA("1312", "13", "Huehuetenango", "12", "La Democracia"),
    HUEHUETENANGO_SAN_MIGUEL_ACATAN("1313", "13", "Huehuetenango", "13", "San Miguel Acatán"),
    HUEHUETENANGO_SAN_RAFAEL_LA_INDEPENDENCIA("1314", "13", "Huehuetenango", "14", "San Rafael La Independencia"),
    HUEHUETENANGO_TODOS_SANTOS_CUCHUMATAN("1315", "13", "Huehuetenango", "15", "Todos Santos Cuchumatán"),
    HUEHUETENANGO_SAN_JUAN_ATITAN("1316", "13", "Huehuetenango", "16", "San Juan Atitán"),
    HUEHUETENANGO_SANTA_EULALIA("1317", "13", "Huehuetenango", "17", "Santa Eulalia"),
    HUEHUETENANGO_SAN_MATEO_IXTATAN("1318", "13", "Huehuetenango", "18", "San Mateo Ixtatán"),
    HUEHUETENANGO_COLOTENANGO("1319", "13", "Huehuetenango", "19", "Colotenango"),
    HUEHUETENANGO_SAN_SEBASTIAN_HUEHUETENANGO("1320", "13", "Huehuetenango", "20", "San Sebastián Huehuetenango"),
    HUEHUETENANGO_TECTITAN("1321", "13", "Huehuetenango", "21", "Tectitán"),
    HUEHUETENANGO_CONCEPCION_HUISTA("1322", "13", "Huehuetenango", "22", "Concepción Huista"),
    HUEHUETENANGO_SAN_JUAN_IXCOY("1323", "13", "Huehuetenango", "23", "San Juan Ixcoy"),
    HUEHUETENANGO_SAN_ANTONIO_HUISTA("1324", "13", "Huehuetenango", "24", "San Antonio Huista"),
    HUEHUETENANGO_SAN_SEBASTIAN_COATAN("1325", "13", "Huehuetenango", "25", "San Sebastián Coatán"),
    HUEHUETENANGO_SANTA_CRUZ_BARILLAS("1326", "13", "Huehuetenango", "26", "Santa Cruz Barillas"),
    HUEHUETENANGO_AGUACATAN("1327", "13", "Huehuetenango", "27", "Aguacatán"),
    HUEHUETENANGO_SAN_RAFAEL_PETZAL("1328", "13", "Huehuetenango", "28", "San Rafael Petzal"),
    HUEHUETENANGO_SAN_GASPAR_IXCHIL("1329", "13", "Huehuetenango", "29", "San Gaspar Ixchil"),
    HUEHUETENANGO_SANTIAGO_CHIMALTENANGO("1330", "13", "Huehuetenango", "30", "Santiago Chimaltenango"),
    HUEHUETENANGO_SANTA_ANA_HUISTA("1331", "13", "Huehuetenango", "31", "Santa Ana Huista"),
    HUEHUETENANGO_UNION_CANTINIL("1332", "13", "Huehuetenango", "32", "Unión Cantinil"),

// Quiche
QUICHE_SANTA_CRUZ_DEL_QUICHE("1401", "14", "Quiché", "01", "Santa Cruz del Quiché"),
    QUICHE_CHICHE("1402", "14", "Quiché", "02", "Chiché"),
    QUICHE_CHINIQUE("1403", "14", "Quiché", "03", "Chinique"),
    QUICHE_ZACUALPA("1404", "14", "Quiché", "04", "Zacualpa"),
    QUICHE_CHAJUL("1405", "14", "Quiché", "05", "Chajul"),
    QUICHE_SANTO_TOMAS_CHICHICASTENANGO("1406", "14", "Quiché", "06", "Sto. Tomás Chichicastenango"),
    QUICHE_PATZITE("1407", "14", "Quiché", "07", "Patzité"),
    QUICHE_SAN_ANTONIO_ILOTENANGO("1408", "14", "Quiché", "08", "San Antonio Ilotenango"),
    QUICHE_SAN_PEDRO_JOCOPILAS("1409", "14", "Quiché", "09", "San Pedro Jocopilas"),
    QUICHE_CUNEN("1410", "14", "Quiché", "10", "Cunén"),
    QUICHE_SAN_JUAN_COTZAL("1411", "14", "Quiché", "11", "San Juan Cotzal"),
    QUICHE_JOYABAJ("1412", "14", "Quiché", "12", "Joyabaj"),
    QUICHE_NEBAJ("1413", "14", "Quiché", "13", "Nebaj"),
    QUICHE_SAN_ANDRES_SAJCABAJA("1414", "14", "Quiché", "14", "San Andrés Sajcabajá"),
    QUICHE_SAN_MIGUEL_USPANTAN("1415", "14", "Quiché", "15", "San Miguel Uspantán"),
    QUICHE_SACAPULAS("1416", "14", "Quiché", "16", "Sacapulas"),
    QUICHE_SAN_BARTOLOME_JOCOTENANGO("1417", "14", "Quiché", "17", "San Bartolomé Jocotenango"),
    QUICHE_CANILLA("1418", "14", "Quiché", "18", "Canillá"),
    QUICHE_CHICAMAN("1419", "14", "Quiché", "19", "Chicamán"),
    QUICHE_IXCAN("1420", "14", "Quiché", "20", "Ixcán"),
    QUICHE_PACHALUM("1421", "14", "Quiché", "21", "Pachalum"),
    QUICHE_PLAYA_GRANDE("1422", "14", "Quiché", "22", "Playa Grande"),

//BAJA_VERAPAZ
BAJA_VERAPAZ_SALAMA("1501", "15", "Baja Verapaz", "01", "Salamá"),
    BAJA_VERAPAZ_SAN_MIGUEL_CHICAJ("1502", "15", "Baja Verapaz", "02", "San Miguel Chicaj"),
    BAJA_VERAPAZ_RABINAL("1503", "15", "Baja Verapaz", "03", "Rabinal"),
    BAJA_VERAPAZ_CUBULCO("1504", "15", "Baja Verapaz", "04", "Cubulco"),
    BAJA_VERAPAZ_GRANADOS("1505", "15", "Baja Verapaz", "05", "Granados"),
    BAJA_VERAPAZ_SANTA_CRUZ_EL_CHOL("1506", "15", "Baja Verapaz", "06", "Santa Cruz El Chol"),
    BAJA_VERAPAZ_SAN_JERONIMO("1507", "15", "Baja Verapaz", "07", "San Jerónimo"),
    BAJA_VERAPAZ_PURULHA("1508", "15", "Baja Verapaz", "08", "Purulhá"),

//    ALTA_VERAPAZ
ALTA_VERAPAZ_COBAN("1601", "16", "Alta Verapaz", "01", "Cobán"),
    ALTA_VERAPAZ_SANTA_CRUZ_VERAPAZ("1602", "16", "Alta Verapaz", "02", "Santa Cruz Verapaz"),
    ALTA_VERAPAZ_SAN_CRISTOBAL_VERAPAZ("1603", "16", "Alta Verapaz", "03", "San Cristóbal Verapaz"),
    ALTA_VERAPAZ_TACTIC("1604", "16", "Alta Verapaz", "04", "Tactic"),
    ALTA_VERAPAZ_TAMAHU("1605", "16", "Alta Verapaz", "05", "Tamahú"),
    ALTA_VERAPAZ_SAN_MIGUEL_TUCURU("1606", "16", "Alta Verapaz", "06", "San Miguel Tucurú"),
    ALTA_VERAPAZ_PANZOS("1607", "16", "Alta Verapaz", "07", "Panzós"),
    ALTA_VERAPAZ_SENAHU("1608", "16", "Alta Verapaz", "08", "Senahú"),
    ALTA_VERAPAZ_SAN_PEDRO_CARCHA("1609", "16", "Alta Verapaz", "09", "San Pedro Carchá"),
    ALTA_VERAPAZ_SAN_JUAN_CHAMELCO("1610", "16", "Alta Verapaz", "10", "San Juan Chamelco"),
    ALTA_VERAPAZ_LANQUIN("1611", "16", "Alta Verapaz", "11", "Lanquín"),
    ALTA_VERAPAZ_SANTA_MARIA_CAHABON("1612", "16", "Alta Verapaz", "12", "Santa María Cahabón"),
    ALTA_VERAPAZ_CHISEC("1613", "16", "Alta Verapaz", "13", "Chisec"),
    ALTA_VERAPAZ_CHAHAL("1614", "16", "Alta Verapaz", "14", "Chahal"),
    ALTA_VERAPAZ_FRAY_BARTOLOME_DE_LAS_CASAS("1615", "16", "Alta Verapaz", "15", "Fray Bartolomé de las Casas"),
    ALTA_VERAPAZ_LA_TINTA("1616", "16", "Alta Verapaz", "16", "La Tinta"),
    ALTA_VERAPAZ_RAXRUHA("1617", "16", "Alta Verapaz", "17", "Raxruhá"),

//    PETEN
PETEN_FLORES("1701", "17", "Petén", "01", "Flores"),
    PETEN_SAN_JOSE("1702", "17", "Petén", "02", "San José"),
    PETEN_SAN_BENITO("1703", "17", "Petén", "03", "San Benito"),
    PETEN_SAN_ANDRES("1704", "17", "Petén", "04", "San Andrés"),
    PETEN_LA_LIBERTAD("1705", "17", "Petén", "05", "La Libertad"),
    PETEN_SAN_FRANCISCO("1706", "17", "Petén", "06", "San Francisco"),
    PETEN_SANTA_ANA("1707", "17", "Petén", "07", "Santa Ana"),
    PETEN_DOLORES("1708", "17", "Petén", "08", "Dolores"),
    PETEN_SAN_LUIS("1709", "17", "Petén", "09", "San Luis"),
    PETEN_SAYAXCHE("1710", "17", "Petén", "10", "Sayaxché"),
    PETEN_MELCHOR_DE_MENCOS("1711", "17", "Petén", "11", "Melchor de Mencos"),
    PETEN_POPTUN("1712", "17", "Petén", "12", "Poptún"),

//    IZABAL
IZABAL_PUERTO_BARRIOS("1801", "18", "Izabal", "01", "Puerto Barrios"),
    IZABAL_LIVINGSTON("1802", "18", "Izabal", "02", "Livingston"),
    IZABAL_EL_ESTOR("1803", "18", "Izabal", "03", "El Estor"),
    IZABAL_MORALES("1804", "18", "Izabal", "04", "Morales"),
    IZABAL_LOS_AMATES("1805", "18", "Izabal", "05", "Los Amates"),

//    Zacapa
ZACAPA_ZACAPA("1901", "19", "Zacapa", "01", "Zacapa"),
    ZACAPA_ESTANZUELA("1902", "19", "Zacapa", "02", "Estanzuela"),
    ZACAPA_RIO_HONDO("1903", "19", "Zacapa", "03", "Río Hondo"),
    ZACAPA_GUALAN("1904", "19", "Zacapa", "04", "Gualán"),
    ZACAPA_TECULUTAN("1905", "19", "Zacapa", "05", "Teculután"),
    ZACAPA_USUMATLAN("1906", "19", "Zacapa", "06", "Usumatlán"),
    ZACAPA_CABANAS("1907", "19", "Zacapa", "07", "Cabañas"),
    ZACAPA_SAN_DIEGO("1908", "19", "Zacapa", "08", "San Diego"),
    ZACAPA_LA_UNION("1909", "19", "Zacapa", "09", "La Unión"),
    ZACAPA_HUITE("1910", "19", "Zacapa", "10", "Huité"),

    CHIQUIMULA_CHIQUIMULA("2001", "20", "Chiquimula", "01", "Chiquimula"),
    CHIQUIMULA_SAN_JOSE_LA_ARADA("2002", "20", "Chiquimula", "02", "San José La Arada"),
    CHIQUIMULA_SAN_JUAN_LA_ERMITA("2003", "20", "Chiquimula", "03", "San Juan La Ermita"),
    CHIQUIMULA_JOCOTAN("2004", "20", "Chiquimula", "04", "Jocotán"),
    CHIQUIMULA_CAMOTAN("2005", "20", "Chiquimula", "05", "Camotán"),
    CHIQUIMULA_OLOPA("2006", "20", "Chiquimula", "06", "Olopa"),
    CHIQUIMULA_ESQUIPULAS("2007", "20", "Chiquimula", "07", "Esquipulas"),
    CHIQUIMULA_CONCEPCION_LAS_MINAS("2008", "20", "Chiquimula", "08", "Concepción Las Minas"),
    CHIQUIMULA_QUEZALTEPEQUE("2009", "20", "Chiquimula", "09", "Quezaltepeque"),
    CHIQUIMULA_SAN_JACINTO("2010", "20", "Chiquimula", "10", "San Jacinto"),
    CHIQUIMULA_IPALA("2011", "20", "Chiquimula", "11", "Ipala"),

//    JALAPA
JALAPA_JALAPA("2101", "21", "Jalapa", "01", "Jalapa"),
    JALAPA_SAN_PEDRO_PINULA("2102", "21", "Jalapa", "02", "San Pedro Pinula"),
    JALAPA_SAN_LUIS_JILOTEPEQUE("2103", "21", "Jalapa", "03", "San Luis Jilotepeque"),
    JALAPA_SAN_MANUEL_CHAPARRON("2104", "21", "Jalapa", "04", "San Manuel Chaparrón"),
    JALAPA_SAN_CARLOS_ALZATATE("2105", "21", "Jalapa", "05", "San Carlos Alzatate"),
    JALAPA_MONJAS("2106", "21", "Jalapa", "06", "Monjas"),
    JALAPA_MATAQUESCUINTLA("2107", "21", "Jalapa", "07", "Mataquescuintla"),

//    JUTIAPA
JUTIAPA_JUTIAPA("2201", "22", "Jutiapa", "01", "Jutiapa"),
    JUTIAPA_EL_PROGRESO("2202", "22", "Jutiapa", "02", "El Progreso"),
    JUTIAPA_SANTA_CATARINA_MITA("2203", "22", "Jutiapa", "03", "Santa Catarina Mita"),
    JUTIAPA_AGUA_BLANCA("2204", "22", "Jutiapa", "04", "Agua Blanca"),
    JUTIAPA_ASUNCION_MITA("2205", "22", "Jutiapa", "05", "Asunción Mita"),
    JUTIAPA_YUPILTEPEQUE("2206", "22", "Jutiapa", "06", "Yupiltepeque"),
    JUTIAPA_ATESCATEMPA("2207", "22", "Jutiapa", "07", "Atescatempa"),
    JUTIAPA_JEREZ("2208", "22", "Jutiapa", "08", "Jerez"),
    JUTIAPA_EL_ADELANTO("2209", "22", "Jutiapa", "09", "El Adelanto"),
    JUTIAPA_ZAPOTITLAN("2210", "22", "Jutiapa", "10", "Zapotitlán"),
    JUTIAPA_COMAPA("2211", "22", "Jutiapa", "11", "Comapa"),
    JUTIAPA_JALPATAGUA("2212", "22", "Jutiapa", "12", "Jalpatagua"),
    JUTIAPA_CONGUACO("2213", "22", "Jutiapa", "13", "Conguaco"),
    JUTIAPA_MOYUTA("2214", "22", "Jutiapa", "14", "Moyuta"),
    JUTIAPA_PASACO("2215", "22", "Jutiapa", "15", "Pasaco"),
    JUTIAPA_SAN_JOSE_ACATEMPA("2216", "22", "Jutiapa", "16", "San José Acatempa"),
    JUTIAPA_QUESADA("2217", "22", "Jutiapa", "17", "Quesada");


    private final String codigo;
    private final String codigoDepartamento;
    private final String nombreDepartamento;
    private final String codigoMunicipio;
    private final String nombreMunicipio;

    CodigoUbicaciones(String codigo, String codigoDepartamento, String nombreDepartamento, String codigoMunicipio, String nombreMunicipio) {
        this.codigo = codigo;
        this.codigoDepartamento = codigoDepartamento;
        this.nombreDepartamento = nombreDepartamento;
        this.codigoMunicipio = codigoMunicipio;
        this.nombreMunicipio = nombreMunicipio;
    }

    public static CodigoUbicaciones fromCodigo(String codigo) {
        for (CodigoUbicaciones ubicacion : values()) {
            if (ubicacion.getCodigo().equals(codigo)) {
                return ubicacion;
            }
        }
        throw new IllegalArgumentException("Código de ubicación no válido: " + codigo);
    }


}
